### ISSUE TITLE
使用这个主题后hexo g出现错误

### ISSUE THREAD

**Issue by Mitpoppy** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#143]
```
Unhandled rejection TypeError: D:\gc\123\themes\Acrylic\layout\index.ejs:6
    4|     <% } %>
    5|     <% if(theme.hometop.banner.enable){ %>
 >> 6|         <%- partial('partial/hometop') %>
    7|     <% } %>
    8| </div>
    9| <main class="layout" id="content-inner">

D:\gc\123\themes\Acrylic\layout\partial\hometop.ejs:5
    3|         <div id="bannerGroup">
    4|             <div id="banners">
 >> 5|                 <%- partial('partial/compoment/hometop/groupTag') %>
    6|             </div>
    7|             <div class="categoryGroup">
    8|                 <%- partial('partial/compoment/hometop/categoryGroup') %>

D:\gc\123\themes\Acrylic\layout\partial\compoment\hometop\groupTag.ejs:12
    10|     <div class="tags-group-wrapper">
    11|         <% for(let i = 1; i <= 2; i++){ %>
 >> 12|             <% for(let j = 0; j < Object.keys(theme.hometop.banner.icon).length; j++){ %>
    13|                 <% const key = Object.keys(theme.hometop.banner.icon)[j] %>
    14|                 <% if(j % 2 == 0){ %>
    15|                     <div class="tags-group-icon-pair">

Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at eval ("D:\\gc\\123\\themes\\Acrylic\\layout\\partial\\compoment\\hometop\\groupTag.ejs":21:34)
    at groupTag (D:\gc\123\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (D:\gc\123\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\gc\123\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\gc\123\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval ("D:\\gc\\123\\themes\\Acrylic\\layout\\partial\\hometop.ejs":12:17)
    at hometop (D:\gc\123\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (D:\gc\123\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\gc\123\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\gc\123\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval ("D:\\gc\\123\\themes\\Acrylic\\layout\\index.ejs":24:17)
    at index (D:\gc\123\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (D:\gc\123\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\gc\123\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\gc\123\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\gc\123\node_modules\bluebird\js\release\util.js:16:23)
    at D:\gc\123\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\gc\123\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

```

**Comment by adil-zhang** [comment]
请更新到最新版本。

**Comment by Mitpoppy** [comment]
> 请更新到最新版本。

主题是新版本啊，是更新hexo吗？

**Comment by adil-zhang** [comment]
> > 请更新到最新版本。
> 
> 主题是新版本啊，是更新hexo吗？

需要更新主题最新版本，main与dev均可以。在后来的版本里做了错误警告。
您的这个问题是由于您开启了banner，但是并没有提供banner.icon， 请调整主题配置文档中的hometop.banner.icon的配置。

**Comment by Mitpoppy** [comment]
> > > 请更新到最新版本。
> > 
> > 
> > 主题是新版本啊，是更新hexo吗？
> 
> 需要更新主题最新版本，main与dev均可以。在后来的版本里做了错误警告。 您的这个问题是由于您开启了banner，但是并没有提供banner.icon， 请调整主题配置文档中的hometop.banner.icon的配置。

我把主题配置文件的banner设置成fales后hexo g成功了，感谢

**Comment by neverup7** [comment]
![}@WVMOB_(_2K}ZBY_P W6GO](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/89000973/692dffda-6d97-407a-bfba-a7a426c9acb3)

PS C:\Users\Never7\Desktop\博客开发\Hexo> hexo s
INFO  Validating config
INFO  
  ===================================================================

       █████╗  ██████╗██████╗ ██╗   ██╗██╗     ██╗ ██████╗
      ██╔══██╗██╔════╝██╔══██╗╚██╗ ██╔╝██║     ██║██╔════╝
      ███████║██║     ██████╔╝ ╚████╔╝ ██║     ██║██║     
      ██╔══██║██║     ██╔══██╗  ╚██╔╝  ██║     ██║██║     
      ██║  ██║╚██████╗██║  ██║   ██║   ███████╗██║╚██████╗
      ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝ ╚═════╝

                        Next-1.1.5
  ===================================================================
INFO  Start processing
ERROR 
 启用banner的情况下，必须提供 icon 图片！
 请在主题配置文件中设置 hometop.banner.icon 选项。
ERROR
 If banner is enabled, icon image must be supplied!
 Please set the hometop.banner.icon option in the theme configuration file.

**最新版**还是有这个bug，把主题配置文件的banner设置成fales才能成功，希望下个版本解决下

**Comment by gtwxxh666** [comment]
首先，我不推荐你放在中文文件夹
其次，请尝试使用dev版本
