### ISSUE TITLE
DEV版本运行报错

### ISSUE THREAD

**Issue by Villode** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#86]
报错如下
 ```
Unhandled rejection TypeError: D:\myisgo\themes\Acrylic\layout\index.ejs:6

   4|     <% } %>
    5|     <% if(theme.hometop.banner.enable){ %>
 >> 6|         <%- partial('partial/hometop') %>
    7|     <% } %>
    8| </div>
    9| <main class="layout" id="content-inner">

D:\myisgo\themes\Acrylic\layout\partial\hometop.ejs:5
    3|         <div id="bannerGroup">
    4|             <div id="banners">
 >> 5|                 <%- partial('partial/compoment/hometop/groupTag') %>
    6|             </div>
    7|             <div class="categoryGroup">
    8|                 <%- partial('partial/compoment/hometop/categoryGroup') %>

D:\myisgo\themes\Acrylic\layout\partial\compoment\hometop\groupTag.ejs:12
    10|     <div class="tags-group-wrapper">
    11|         <% for(let i = 1; i <= 2; i++){ %>
 >> 12|             <% for(let j = 0; j < Object.keys(theme.hometop.banner.icon).length; j++){ %>
    13|                 <% const key = Object.keys(theme.hometop.banner.icon)[j] %>
    14|                 <% if(j % 2 == 0){ %>
    15|                     <div class="tags-group-icon-pair">

Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at eval ("D:\\myisgo\\themes\\Acrylic\\layout\\partial\\compoment\\hometop\\groupTag.ejs":21:34)
    at groupTag (D:\myisgo\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (D:\myisgo\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\myisgo\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\myisgo\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval ("D:\\myisgo\\themes\\Acrylic\\layout\\partial\\hometop.ejs":12:17)
    at hometop (D:\myisgo\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (D:\myisgo\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\myisgo\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\myisgo\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval ("D:\\myisgo\\themes\\Acrylic\\layout\\index.ejs":24:17)
    at index (D:\myisgo\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (D:\myisgo\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\myisgo\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\myisgo\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\myisgo\node_modules\bluebird\js\release\util.js:16:23)
    at D:\myisgo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\myisgo\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by Villode** [comment]
themes\\Acrylic\\layout\\partial\\compoment\\hometop\\groupTag.ejs 
我修改了11-24行为这样就没有报错了
        <% if (theme.hometop.banner.icon) { %>
            <% for(let j = 0; j < Object.keys(theme.hometop.banner.icon).length; j++){ %>
                <% const key = Object.keys(theme.hometop.banner.icon)[j] %>
                <% if(j % 2 == 0){ %>
                    <div class="tags-group-icon-pair">
                <% } %>    
                    <div class="tags-group-icon" style="background: <%- theme.hometop.banner.icon[key].color %>">
                        <img src="<%= theme.hometop.banner.icon[key].img %>" title="<%= key %>">
                    </div>
                <% if(j % 2 == 1 || j == Object.keys(theme.hometop.banner.icon).length - 1){ %>
                    </div>
                <% } %>
            <% } %>
        <% } %>

**Comment by Villode** [comment]
themes\Acrylic\layout\partial\compoment\hometop\groupTag.ejs
我修改了11-24行，就没有报错了
`        <% if (theme.hometop.banner.icon) { %>
            <% for(let j = 0; j < Object.keys(theme.hometop.banner.icon).length; j++){ %>
                <% const key = Object.keys(theme.hometop.banner.icon)[j] %>
                <% if(j % 2 == 0){ %>
                    <div class="tags-group-icon-pair">
                <% } %>    
                    <div class="tags-group-icon" style="background: <%- theme.hometop.banner.icon[key].color %>">
                        <img src="<%= theme.hometop.banner.icon[key].img %>" title="<%= key %>">
                    </div>
                <% if(j % 2 == 1 || j == Object.keys(theme.hometop.banner.icon).length - 1){ %>
                    </div>
                <% } %>
            <% } %>
        <% } %>   `

**Comment by adil-zhang** [comment]
请在生成前，将配置文件中`hometop.banner.icon`中的内容取消注释并替换为您自己的内容。
